const canvas=document.getElementById('screen'),ctx=canvas.getContext('2d'),raw=document.createElement('canvas'),rc=raw.getContext('2d');
const statusText=document.getElementById('status'),notice=document.getElementById('notice'),shot=document.getElementById('shot');
let worker=null,rotation=0,active=false,hasFrame=false,nextRetry=0,pollTimer,polling=false;
function clearView(message){if(worker){worker.terminate();worker=null}active=false;hasFrame=false;ctx.clearRect(0,0,canvas.width,canvas.height);rc.clearRect(0,0,raw.width,raw.height);canvas.style.display='none';notice.hidden=false;notice.textContent=message;shot.disabled=true;statusText.textContent=message}
function draw(){if(!hasFrame)return;const sideways=rotation%180!==0;canvas.width=sideways?raw.height:raw.width;canvas.height=sideways?raw.width:raw.height;ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(raw,-raw.width/2,-raw.height/2);canvas.style.display='block';notice.hidden=true;shot.disabled=false;statusText.textContent='Live'}
function begin(state){active=true;raw.width=state.width;raw.height=state.height;const current=new Worker('/worker_stream_processing.js');worker=current;current.onmessage=({data})=>{if(worker!==current||!active)return;if(data.type==='update'){const src=data.data,pixels=new Uint8ClampedArray(src.length);for(let i=0;i<src.length;i+=4){pixels[i]=src[i+2];pixels[i+1]=src[i+1];pixels[i+2]=src[i];pixels[i+3]=255}rc.putImageData(new ImageData(pixels,raw.width,raw.height),0,0);hasFrame=true;draw()}else if(data.type==='error'){clearView(data.code==='RATE_LIMITED'?'Viewer busy — retrying shortly':'Reconnecting…');nextRetry=Date.now()+4000}};current.onerror=()=>{clearView('Connection interrupted');nextRetry=Date.now()+4000};current.postMessage({type:'init',width:state.width,height:state.height,rate:200})}
async function poll(){clearTimeout(pollTimer);if(polling||document.hidden)return;polling=true;try{const r=await fetch('/state',{cache:'no-store',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error();const s=await r.json();if(document.hidden)return;if(!s.sharing){clearView('Not currently sharing');return}if(rotation!==s.rotation){rotation=s.rotation;draw()}if(!worker&&Date.now()>=nextRetry)begin(s)}catch{clearView('Offline — waiting for tablet')}finally{polling=false;if(!document.hidden)pollTimer=setTimeout(poll,active?1000:15000)}}
document.addEventListener('visibilitychange',()=>{clearTimeout(pollTimer);if(document.hidden)clearView('Paused while tab is hidden');else poll()});
document.getElementById('full').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{})};
shot.onclick=()=>{if(!active||!hasFrame)return;canvas.toBlob(blob=>{if(!blob||!active)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='remarkable-live.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')};poll();
